repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key # IMPEDE SUBIR SENHAS!

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix ] # Arruma erros de Python sozinho!

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black # Deixa o código com visual profissional padrão